name: "Netdrive-upload"
description: "网盘文件上传,目前支持小飞机网盘|蓝奏云优享等"
author: "Wes Lin"
inputs:
  files:
    description: "需要上传文件(支持通配符)"
    required: true

  drive-type:
    description: "网盘类型 (支持: feijipan/ilanzou)"
    required: true

  dest-path:
    description: "目标文件夹路径"
    required: false
    default: ""

  username:
    description: "账号"
    required: true

  password:
    description: "密码"
    required: true

  uuid:
    description: "设备uuid"
    required: false
    default: ""

  debug:
    description: "是否输出调试日志"

runs:
  using: "node20"
  main: "dist/index.js"
branding:
  color: "green"
  icon: "package"
