name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: "build and release"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Build Netdrive SDK
        run: |
          cd netdrive-sdk && pnpm install && pnpm build
          
      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Commit and Push Changes
        run: |
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git add .
          git commit -m "Action version ${{ github.ref }} release"
          git push origin HEAD:main