name: Test

on:
  workflow_dispatch:

jobs:
  upload:
    name: "Test upload"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Create dist directory (if not exists)
        run: mkdir -p dist

      - name: Generate 5MB random text file
        run: |
          FILENAME="random_$(date +%s)_${RANDOM}.txt"

          dd if=/dev/urandom of="dist/$FILENAME" bs=1024 count=5120

          ls -lh "dist/$FILENAME"

      - name: Upload to Netdrive
        uses: wes-lin/action-netdrive-upload@main
        with:
          username: ${{ secrets.NET_DRIVE_USERNAME }}
          password: ${{ secrets.NET_DRIVE_PASSWORD }}
          debug: ${{ vars.DEBUG }}
          drive-type: feijipan
          dest-path: 测试目录/缓存
          files: |
            dist/*.txt
