name: Test

on:
  workflow_dispatch:

jobs:
  upload:
    name: "Test upload"
    runs-on: ubuntu-latest

    steps:
      - name: Create .cache directory (if not exists)
        run: mkdir -p .cache

      - name: Generate 5MB random text file
        run: |
          FILENAME="random_$(date +%s)_${RANDOM}.txt"

          dd if=/dev/urandom of=".cache/$FILENAME" bs=1024 count=5120

          ls -lh ".cache/$FILENAME"

      - name: Upload to Netdrive
        uses: wes-lin/action-netdrive-upload@main
        with:
          username: ${{ secrets.NET_DRIVE_USERNAME }}
          password: ${{ secrets.NET_DRIVE_PASSWORD }}
          debug: ${{ vars.DEBUG }}
          drive-type: ilanzou
          dest-path: 测试目录/缓存
          files: |
            .cache/*.txt
