name: Test

on:
  workflow_dispatch:

jobs:
  upload:
    name: "Test upload"
    runs-on: ubuntu-latest

    steps:
      - name: Create .cache directory (if not exists)
        run: mkdir -p .cache

      - name: Generate random filename and create file
        run: |
          FILENAME="random_$RANDOM.txt"

          echo "Random text generated at $(date)" > ".cache/$FILENAME"
          echo "Random number: $RANDOM" >> ".cache/$FILENAME"

          echo "File created at: .cache/$FILENAME"
          cat ".cache/$FILENAME"

      - name: Upload to Netdrive
        uses: wes-lin/action-netdrive-upload@main
        with:
          username: ${{ secrets.NET_DRIVE_USERNAME }}
          password: ${{ secrets.NET_DRIVE_PASSWORD }}
          debug: ${{ vars.DEBUG }}
          drive-type: ilanzou
          dest-path: 测试目录/缓存
          files: |
            .cache/*.txt
